### ISSUE TITLE
Context menu: "link to preview" does not work

### ISSUE THREAD

**Issue by ML-procitec** [procitec/qtcreator-sphinx-plugin#1]
After I have parameterized the URL, no preview is displayed.

**Comment by kreuzberger** [comment]
This is currently not implemented due to issues what to use as help browser
Alternatives are:

- WebEngine
- qlighthtml (see https://bugreports.qt.io/browse/QTBUG-78278)

Usage of WebEngine would bloat the plugin, but is currently best option to show webcontent.
Alternatively the QTextBrowser could be used for the preview, just too see if everything is ok with the syntax.

**Comment by kreuzberger** [comment]
Due to [https://bugreports.qt.io/browse/QTCREATORBUG-24330](https://bugreports.qt.io/browse/QTCREATORBUG-24330) the qlitehtml library could be used to display the preview page

**Comment by kreuzberger** [comment]
With the qtc-4.14 Release the qlitehtml could be used to preview the html page. Seems to be very more useful than QTextBrowser.
Snapshot Release builds with the qlitehtml.

**Comment by kreuzberger** [comment]
Using qlitehtml, is supported now stable in qtcreator
